// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module TLSerdesser_boom(
  input         clock,
                reset,
                auto_client_out_a_ready,
                auto_client_out_d_valid,
  input  [2:0]  auto_client_out_d_bits_opcode,
  input  [1:0]  auto_client_out_d_bits_param,
  input  [3:0]  auto_client_out_d_bits_size,
                auto_client_out_d_bits_source,
  input  [2:0]  auto_client_out_d_bits_sink,
  input         auto_client_out_d_bits_denied,
  input  [63:0] auto_client_out_d_bits_data,
  input         auto_client_out_d_bits_corrupt,
                io_ser_in_valid,
  input  [31:0] io_ser_in_bits,
  input         io_ser_out_ready,
  output        auto_client_out_a_valid,
  output [2:0]  auto_client_out_a_bits_opcode,
                auto_client_out_a_bits_param,
  output [3:0]  auto_client_out_a_bits_size,
                auto_client_out_a_bits_source,
  output [31:0] auto_client_out_a_bits_address,
  output [7:0]  auto_client_out_a_bits_mask,
  output [63:0] auto_client_out_a_bits_data,
  output        auto_client_out_a_bits_corrupt,
                auto_client_out_d_ready,
                io_ser_in_ready,
                io_ser_out_valid,
  output [31:0] io_ser_out_bits
);

  wire        _inDes_io_out_valid;	// @[Serdes.scala:645:23]
  wire [2:0]  _inDes_io_out_bits_chanId;	// @[Serdes.scala:645:23]
  wire [7:0]  _inDes_io_out_bits_size;	// @[Serdes.scala:645:23]
  wire [7:0]  _inDes_io_out_bits_source;	// @[Serdes.scala:645:23]
  wire [63:0] _inDes_io_out_bits_address;	// @[Serdes.scala:645:23]
  wire [8:0]  _inDes_io_out_bits_union;	// @[Serdes.scala:645:23]
  wire        _outSer_io_in_ready;	// @[Serdes.scala:640:24]
  wire        _outArb_io_in_1_ready;	// @[Serdes.scala:638:24]
  wire        _outArb_io_out_valid;	// @[Serdes.scala:638:24]
  wire [2:0]  _outArb_io_out_bits_chanId;	// @[Serdes.scala:638:24]
  wire [2:0]  _outArb_io_out_bits_opcode;	// @[Serdes.scala:638:24]
  wire [2:0]  _outArb_io_out_bits_param;	// @[Serdes.scala:638:24]
  wire [7:0]  _outArb_io_out_bits_size;	// @[Serdes.scala:638:24]
  wire [7:0]  _outArb_io_out_bits_source;	// @[Serdes.scala:638:24]
  wire [63:0] _outArb_io_out_bits_data;	// @[Serdes.scala:638:24]
  wire        _outArb_io_out_bits_corrupt;	// @[Serdes.scala:638:24]
  wire [8:0]  _outArb_io_out_bits_union;	// @[Serdes.scala:638:24]
  wire        _outArb_io_out_bits_last;	// @[Serdes.scala:638:24]
  wire [26:0] _merged_bits_last_beats1_decode_T_1 = 27'hFFF << auto_client_out_d_bits_size;	// @[package.scala:235:71]
  reg  [8:0]  merged_bits_last_counter_1;	// @[Edges.scala:229:27]
  wire        _inDes_io_out_ready_T = _inDes_io_out_bits_chanId == 3'h0;	// @[Serdes.scala:234:37, :645:23]
  always @(posedge clock) begin
    if (reset)
      merged_bits_last_counter_1 <= 9'h0;	// @[Edges.scala:229:27]
    else if (_outArb_io_in_1_ready & auto_client_out_d_valid) begin	// @[Decoupled.scala:51:35, Serdes.scala:638:24]
      if (merged_bits_last_counter_1 == 9'h0) begin	// @[Edges.scala:229:27, :231:25]
        if (auto_client_out_d_bits_opcode[0])	// @[Edges.scala:106:36]
          merged_bits_last_counter_1 <= ~(_merged_bits_last_beats1_decode_T_1[11:3]);	// @[Edges.scala:229:27, package.scala:235:{46,71,76}]
        else	// @[Edges.scala:106:36]
          merged_bits_last_counter_1 <= 9'h0;	// @[Edges.scala:229:27]
      end
      else	// @[Edges.scala:231:25]
        merged_bits_last_counter_1 <= merged_bits_last_counter_1 - 9'h1;	// @[Edges.scala:229:27, :230:28]
    end
  end // always @(posedge)
  `ifndef SYNTHESIS
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        merged_bits_last_counter_1 = _RANDOM_0[17:9];	// @[Edges.scala:229:27]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  HellaPeekingArbiter_boom outArb (	// @[Serdes.scala:638:24]
    .clock                (clock),
    .reset                (reset),
    .io_in_1_valid        (auto_client_out_d_valid),
    .io_in_1_bits_opcode  (auto_client_out_d_bits_opcode),
    .io_in_1_bits_param   ({1'h0, auto_client_out_d_bits_param}),	// @[Serdes.scala:312:20, :623:72]
    .io_in_1_bits_size    ({4'h0, auto_client_out_d_bits_size}),	// @[Serdes.scala:313:20]
    .io_in_1_bits_source  ({4'h0, auto_client_out_d_bits_source}),	// @[Serdes.scala:313:20, :314:20]
    .io_in_1_bits_data    (auto_client_out_d_bits_data),
    .io_in_1_bits_corrupt (auto_client_out_d_bits_corrupt),
    .io_in_1_bits_union   ({5'h0, auto_client_out_d_bits_sink, auto_client_out_d_bits_denied}),	// @[Serdes.scala:319:22]
    .io_in_1_bits_last    (merged_bits_last_counter_1 == 9'h1 | (auto_client_out_d_bits_opcode[0] ? ~(_merged_bits_last_beats1_decode_T_1[11:3]) : 9'h0) == 9'h0),	// @[Edges.scala:106:36, :221:14, :229:27, :232:{25,33,43}, package.scala:235:{46,71,76}]
    .io_out_ready         (_outSer_io_in_ready),	// @[Serdes.scala:640:24]
    .io_in_1_ready        (_outArb_io_in_1_ready),
    .io_out_valid         (_outArb_io_out_valid),
    .io_out_bits_chanId   (_outArb_io_out_bits_chanId),
    .io_out_bits_opcode   (_outArb_io_out_bits_opcode),
    .io_out_bits_param    (_outArb_io_out_bits_param),
    .io_out_bits_size     (_outArb_io_out_bits_size),
    .io_out_bits_source   (_outArb_io_out_bits_source),
    .io_out_bits_data     (_outArb_io_out_bits_data),
    .io_out_bits_corrupt  (_outArb_io_out_bits_corrupt),
    .io_out_bits_union    (_outArb_io_out_bits_union),
    .io_out_bits_last     (_outArb_io_out_bits_last)
  );
  GenericSerializer_boom outSer (	// @[Serdes.scala:640:24]
    .clock              (clock),
    .reset              (reset),
    .io_in_valid        (_outArb_io_out_valid),	// @[Serdes.scala:638:24]
    .io_in_bits_chanId  (_outArb_io_out_bits_chanId),	// @[Serdes.scala:638:24]
    .io_in_bits_opcode  (_outArb_io_out_bits_opcode),	// @[Serdes.scala:638:24]
    .io_in_bits_param   (_outArb_io_out_bits_param),	// @[Serdes.scala:638:24]
    .io_in_bits_size    (_outArb_io_out_bits_size),	// @[Serdes.scala:638:24]
    .io_in_bits_source  (_outArb_io_out_bits_source),	// @[Serdes.scala:638:24]
    .io_in_bits_address (64'h0),	// @[Serdes.scala:638:24]
    .io_in_bits_data    (_outArb_io_out_bits_data),	// @[Serdes.scala:638:24]
    .io_in_bits_corrupt (_outArb_io_out_bits_corrupt),	// @[Serdes.scala:638:24]
    .io_in_bits_union   (_outArb_io_out_bits_union),	// @[Serdes.scala:638:24]
    .io_in_bits_last    (_outArb_io_out_bits_last),	// @[Serdes.scala:638:24]
    .io_out_ready       (io_ser_out_ready),
    .io_in_ready        (_outSer_io_in_ready),
    .io_out_valid       (io_ser_out_valid),
    .io_out_bits        (io_ser_out_bits)
  );
  GenericDeserializer_boom inDes (	// @[Serdes.scala:645:23]
    .clock               (clock),
    .reset               (reset),
    .io_in_valid         (io_ser_in_valid),
    .io_in_bits          (io_ser_in_bits),
    .io_out_ready        (~(_inDes_io_out_bits_chanId == 3'h4 | _inDes_io_out_bits_chanId == 3'h3 | _inDes_io_out_bits_chanId == 3'h2 | _inDes_io_out_bits_chanId == 3'h1) & _inDes_io_out_ready_T & auto_client_out_a_ready),	// @[Mux.scala:81:58, Serdes.scala:234:37, :235:37, :236:37, :237:37, :238:37, :331:20, :645:23]
    .io_in_ready         (io_ser_in_ready),
    .io_out_valid        (_inDes_io_out_valid),
    .io_out_bits_chanId  (_inDes_io_out_bits_chanId),
    .io_out_bits_opcode  (auto_client_out_a_bits_opcode),
    .io_out_bits_param   (auto_client_out_a_bits_param),
    .io_out_bits_size    (_inDes_io_out_bits_size),
    .io_out_bits_source  (_inDes_io_out_bits_source),
    .io_out_bits_address (_inDes_io_out_bits_address),
    .io_out_bits_data    (auto_client_out_a_bits_data),
    .io_out_bits_corrupt (auto_client_out_a_bits_corrupt),
    .io_out_bits_union   (_inDes_io_out_bits_union)
  );
  assign auto_client_out_a_valid = _inDes_io_out_valid & _inDes_io_out_ready_T;	// @[Serdes.scala:234:37, :645:23, :647:45]
  assign auto_client_out_a_bits_size = _inDes_io_out_bits_size[3:0];	// @[Serdes.scala:372:15, :645:23]
  assign auto_client_out_a_bits_source = _inDes_io_out_bits_source[3:0];	// @[Serdes.scala:373:15, :645:23]
  assign auto_client_out_a_bits_address = _inDes_io_out_bits_address[31:0];	// @[Serdes.scala:374:15, :645:23]
  assign auto_client_out_a_bits_mask = _inDes_io_out_bits_union[7:0];	// @[Serdes.scala:380:15, :645:23]
  assign auto_client_out_d_ready = _outArb_io_in_1_ready;	// @[Serdes.scala:638:24]
endmodule

