
lappend DEF_MACROS RANDOMIZE_REG_INIT
lappend DEF_MACROS RANDOMIZE_MEM_INIT
lappend DEF_MACROS "RANDOM=32'h0"
lappend DEF_MACROS "PRINTF_COND=0"

set BOOM_CONFIG chipyard.harness.TestHarness.MediumPFBoomMmioJtagUartConfig
set suffix boom


lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_69_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/BankedStore_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AsyncQueueSink_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLAsyncCrossingSource_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_15_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_59_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AsyncQueueSink_3_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/PipelinedMulUnit_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TageTable_3_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_113_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/BoomRAS_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLFragmenter_7_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/PMPChecker_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLInterconnectCoupler_15_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/JtagBypassChain_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/DivSqrtRecF64_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLSerdesser_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ListBuffer_2_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLXbar_8_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/head_combMem_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/IntToFPUnit_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLFragmenter_6_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/cc_banks_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_62_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/regfile_combMem_0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Arbiter_19_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLFragmenter_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ALUUnit_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RenameMapTable_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLInterconnectCoupler_17_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_35_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Arbiter_15_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/FpPipeline_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Arbiter_18_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/BoomTile_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Repeater_3_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLInterconnectCoupler_9_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/DMIToTL_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_34_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLXbar_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RenameBusyTable_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/MulAddRecFNPipe_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AXI4Fragmenter_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/IssueUnitCollapsing_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/IssueSlot_16_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_63_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLBuffer_16_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLXbar_10_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Arbiter_3_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ClockGroupParameterModifier_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/dataArrayWay_3_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_122_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/SinkE_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ResetCatchAndSync_d3_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ForwardingAgeLogic_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/BIMBranchPredictorBank_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_43_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/BoomMSHR_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RegisterRead_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_72_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ALUUnit_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Atomics_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AsyncResetSynchronizerPrimitiveShiftReg_d3_i0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_105_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_130_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/BoomFrontend_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TageTable_5_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/FixedClockBroadcast_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_61_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_51_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/FetchTargetQueue_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/IntToFP_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TilePRCIDomain_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/hi_us_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/BoomNonBlockingDCache_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RegisterReadDecode_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/array_0_0_0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/dataArrayWay_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AXI4IdIndexer_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/NonSyncResetSynchronizerPrimitiveShiftReg_d3_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_83_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Arbiter_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TageTable_2_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RegisterReadDecode_3_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_53_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RVCExpander_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/BranchKillableQueue_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/CSRFile_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/SinkX_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/regfile_combMem_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_2_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_111_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_54_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/cc_banks_2_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/FAMicroBTBBranchPredictorBank_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_65_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/BasicDispatcher_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ICache_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RecFNToIN_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RegisterReadDecode_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_20_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_53_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/meta_0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ClockSinkDomain_2_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/UARTTx_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/BranchKillableQueue_2_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Arbiter_16_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_27_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLFragmenter_5_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_124_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/BranchKillableQueue_5_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_40_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLDebugModuleInnerAsync_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Arbiter_20_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/PipelinedMultiplier_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ListBuffer_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/data_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RegisterFileSynthesizable_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/next_combMem_0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Arbiter_8_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLInterconnectCoupler_7_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Repeater_7_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ghist_0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLWidthWidget_8_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Repeater_9_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/DivSqrtRecF64_mulAddZ31_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_data_combMem_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/head_combMem_0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLBuffer_5_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TageTable_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLInterconnectCoupler_4_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/SynchronizerShiftReg_w8_d3_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/IssueUnitCollapsing_2_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLError_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLCacheCork_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/dataArrayWay_2_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Arbiter_12_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ClockGroupAggregator_6_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/cc_banks_0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/SourceA_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RoundRawFNToRecFN_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ALUExeUnit_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/IntSyncCrossingSource_5_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_121_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLDebugModuleOuter_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_21_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/BoomDuplicatedDataArray_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_25_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ClockSinkDomain_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Repeater_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/FixedClockBroadcast_3_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_6_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/IssueUnitCollapsing_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/FPUFMAPipe_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/tail_combMem_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLUART_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RenameMapTable_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/IntSyncCrossingSource_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TageTable_4_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/DivUnit_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/FPUFMAPipe_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/data_combMem_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_30_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/FPUExeUnit_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/FDivSqrtUnit_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/rob_debug_wdata_combMem_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_18_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLB_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/INToRecFN_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_23_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/IntSyncCrossingSource_8_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_114_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Arbiter_14_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/MulAddRecFNToRaw_preMul_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/FMADecoder_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLInterconnectCoupler_8_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_103_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Arbiter_2_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Arbiter_5_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/SourceD_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/lo_us_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_sink_combMem_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TageBranchPredictorBank_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/BranchMaskGenerationLogic_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/UOPCodeFDivDecoder_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AXI4Deinterleaver_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLXbar_11_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TileClockGater_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RoundAnyRawFNToRecFN_3_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/hi_us_4_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_4_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_7_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/PeripheryBus_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/array_2_0_0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/lo_us_3_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_129_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLWidthWidget_4_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/OptimizationBarrier_36_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/hi_us_0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AsyncQueueSource_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AsyncResetRegVec_w1_i1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_76_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/SourceX_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ALU_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/DebugTransportModuleJTAG_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/MaxPeriodFibonacciLFSR_3_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RenameFreeList_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/CLINT_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Arbiter_7_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RegisterFileSynthesizable_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLBuffer_12_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RoundAnyRawFNToRecFN_2_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/SourceB_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_5_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_49_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLError_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/GenericDeserializer_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AsyncValidSync_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_48_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RenameStage_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ComposedBranchPredictorBank_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RoundAnyRawFNToRecFN_5_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLFragmenter_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLFragmenter_3_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/table_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_117_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_108_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AsyncQueueSink_2_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/JtagStateMachine_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_17_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/head_combMem_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/BoomProbeUnit_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/OptimizationBarrier_35_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/FixedClockBroadcast_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/cc_banks_3_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/btb_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/hi_us_3_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_37_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_39_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ClockCrossingReg_w32_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_120_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AsyncQueue_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_80_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLDebugModuleInner_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/DecodeUnit_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/data_combMem_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RenameStage_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLInterconnectCoupler_5_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ClockCrossingReg_w55_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_22_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/INToRecFN_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLROM_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/DigitalTop_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLInterconnectCoupler_12_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/CaptureUpdateChain_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_5_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/table_0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/lo_us_2_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/DivSqrtRecF64ToRaw_mulAddZ31_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AXI4ToTL_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Mul54_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLFIFOFixer_4_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/table_2_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_52_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ghist_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_50_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/SystemBus_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_14_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/tag_array_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/lb_combMem_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/lo_us_4_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AsyncResetRegVec_w2_i0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_37_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/table_4_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/hi_us_2_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLDebugModuleOuterAsync_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLXbar_3_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/next_combMem_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/MulAddRecFNToRaw_postMul_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/IntSyncCrossingSource_4_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/BTBBranchPredictorBank_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/data_combMem_0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/IntSyncAsyncCrossingSink_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/meta_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RoundAnyRawFNToRecFN_4_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/hi_us_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/LoopBranchPredictorBank_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/SinkC_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RoundRawFNToRecFN_2_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/lo_us_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLInterconnectCoupler_11_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/BoomCore_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/JtagTapController_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLFIFOFixer_3_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_28_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/tail_combMem_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/OptimizationBarrier_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AXI4IdIndexer_2_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/l2_tlb_ram_0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/GenericSerializer_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/table_0_0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Arbiter_6_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TageTable_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_64_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_123_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_55_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AsyncQueueSink_4_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RecFNToIN_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_10_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/HellaCacheArbiter_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RegisterReadDecode_2_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLInterconnectCoupler_14_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLDebugModule_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RecFNToRecFN_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_41_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/IntSyncSyncCrossingSink_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/OptimizationBarrier_14_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Repeater_4_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_33_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_77_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ALUExeUnit_2_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/tag_array_0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AXI4UserYanker_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/MemAddrCalcUnit_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ClockCrossingReg_w15_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/tail_combMem_0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/NLPrefetcher_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/meta_0_0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/array_1_0_0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLBuffer_9_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Repeater_8_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/CaptureUpdateChain_2_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/CaptureUpdateChain_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/dataArrayWay_0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/PeripheryBus_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/IssueSlot_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RoundAnyRawFNToRecFN_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_56_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLBuffer_4_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/table_3_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ebtb_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/SinkD_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_55_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AsyncResetRegVec_w8_i0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/CompareRecFN_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_9_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLToAXI4_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_56_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Arbiter_4_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLXbar_2_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ClockGroupCombiner_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_109_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AMOALU_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ListBuffer_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/IntXbar_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Repeater_2_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLBuffer_2_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_107_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLFIFOFixer_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/btb_0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_75_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/CaptureChain_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_8_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/sdq_combMem_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/BranchKillableQueue_3_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/BundleBridgeNexus_15_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_36_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_104_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Directory_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_112_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/plusarg_reader_$suffix.v
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_46_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_38_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/IntSyncAsyncCrossingSink_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_42_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_29_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/next_combMem_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLXbar_5_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLAtomicAutomata_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLXbar_4_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_125_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLPLIC_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/SourceE_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_126_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/lo_us_0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_116_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AsyncQueueSource_4_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/SinkA_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_24_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AsyncQueueSource_2_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/PLICFanIn_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLToAXI4_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_6_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RenameBusyTable_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ClockSinkDomain_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ProbePicker_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/HellaPeekingArbiter_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/FetchBuffer_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_54_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TileResetSetter_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RoundRawFNToRecFN_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/InclusiveCacheBankScheduler_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_127_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLFIFOFixer_5_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLFIFOFixer_2_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLInterconnectCoupler_19_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_address_combMem_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/CoherenceManagerWrapper_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/NBDTLB_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/UARTRx_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/rob_debug_inst_mem_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/FPU_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Rob_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/LevelGateway_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLFragmenter_2_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/cc_dir_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Arbiter_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_26_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AsyncResetRegVec_w1_i0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLAtomicAutomata_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AsyncResetSynchronizerShiftReg_w1_d3_i0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_32_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_44_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/UOPCodeFPUDecoder_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLBusBypass_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLInterconnectCoupler_6_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLBusBypassBar_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_106_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Repeater_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AsyncResetSynchronizerShiftReg_w4_d3_i0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLBuffer_3_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ClockGroupParameterModifier_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_12_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/BranchPredictor_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RoundAnyRawFNToRecFN_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/SynchronizerShiftReg_w1_d3_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AsyncQueueSource_3_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_81_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/MulAddRecFNPipe_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RegisterRead_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/MulAddRecFNToRaw_postMul_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/LSU_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RecFNToRecFN_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLBuffer_7_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/FPToFP_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/MaxPeriodFibonacciLFSR_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AXI4IdIndexer_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_31_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_71_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLBuffer_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_60_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/PTW_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/BranchKillableQueue_4_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Repeater_6_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/InclusiveCache_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/MulDiv_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/IntXbar_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RenameFreeList_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/array_3_0_0_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_74_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/FrontBus_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ErrorDeviceWrapper_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ClockGroupResetSynchronizer_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AXI4UserYanker_2_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/BoomWritebackUnit_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/SourceC_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/FPToInt_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AsyncResetSynchronizerShiftReg_w1_d3_i0_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_115_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/MulAddRecFNToRaw_preMul_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Arbiter_10_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/LoopBranchPredictorColumn_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_110_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/BranchDecode_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLFIFOFixer_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ram_combMem_3_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/RoundAnyRawFNToRecFN_7_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/IntSyncSyncCrossingSink_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/MemoryBus_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLBuffer_6_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/L1MetadataArray_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/BoomIOMSHR_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/MSHR_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/FPUUnit_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/TLAsyncCrossingSink_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AXI4Buffer_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ALUExeUnit_1_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/BoomMSHRFile_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ClockCrossingReg_w43_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/AXI4UserYanker_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/Queue_79_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/IDPool_$suffix.sv
lappend VERILOG_FILES $REPO_DIR/boom/source/IP/$BOOM_CONFIG/gen-collateral/ClockSinkDomain_3_$suffix.sv

lappend VERILOG_FILES $REPO_DIR/boom/source/rtl/verilog/mem_ext_mediumboom.v
lappend VERILOG_FILES $REPO_DIR/boom/source/rtl/verilog/boom_trace.v
lappend VERILOG_FILES $REPO_DIR/boom/source/rtl/verilog/boom_ctrl.v
lappend VERILOG_FILES $REPO_DIR/boom/source/rtl/verilog/boom_core.v
lappend VERILOG_FILES $REPO_DIR/boom/source/rtl/verilog/boom_regfile.v
lappend VERILOG_FILES $REPO_DIR/boom/source/rtl/verilog/boom_wrap.v
lappend VERILOG_FILES $REPO_DIR/boom/source/rtl/verilog/pm_boom.v


