
lappend DEF_MACROS RANDOMIZE_REG_INIT
lappend DEF_MACROS RANDOMIZE_MEM_INIT
lappend DEF_MACROS "PRINTF_COND=0"

set ROCKET_CONFIG chipyard.harness.TestHarness.BigRocketMmioJtagUartConfig

lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/IntXbar_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_111.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/SinkA.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/RocketTile.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/LevelGateway.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_20.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Repeater_2.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_53.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/IBuf.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/SourceD.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_5.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/CaptureUpdateChain_2.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_36.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLInterconnectCoupler_15.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TileResetSetter.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ClockSinkDomain_3.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLInterconnectCoupler_6.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_18.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_103.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/IntSyncAsyncCrossingSink.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLBuffer_2.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLFIFOFixer_4.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AsyncResetSynchronizerShiftReg_w1_d3_i0_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/CSRFile.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Atomics.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLUART.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/NonSyncResetSynchronizerPrimitiveShiftReg_d3.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_8.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLFIFOFixer_3.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AsyncQueueSource_3.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Repeater_6.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_76.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/IntSyncCrossingSource_8.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/data_combMem_0.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/INToRecFN.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_40.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_35.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/plusarg_reader.v
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_113.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/DivSqrtRawFN_small_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/PlusArgTimeout.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_37.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_72.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AsyncQueueSink.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/UARTRx.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_address_combMem.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/PeripheryBus_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_21.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/RoundAnyRawFNToRecFN_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLInterconnectCoupler_7.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ErrorDeviceWrapper.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ClockSinkDomain.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/HellaCacheArbiter.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLInterconnectCoupler_17.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLBuffer_5.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLBuffer_3.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLInterconnectCoupler_19.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/BreakpointUnit.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_37.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLDebugModuleOuter.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AXI4UserYanker_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLBusBypass.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/FPUFMAPipe_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_9.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_3.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLFragmenter.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLFragmenter_3.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_10.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AsyncResetRegVec_w8_i0.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/data_arrays_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_32.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/SynchronizerShiftReg_w1_d3.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/IDPool.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/FPToFP.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/RoundRawFNToRecFN_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/DebugTransportModuleJTAG.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/tag_array.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_107.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLInterconnectCoupler_8.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_44.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_29.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/PLICFanIn.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AsyncQueueSink_3.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AXI4ToTL.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/SinkE.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLBuffer.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_42.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/GenericDeserializer.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_7.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_15.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_25.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ClockGroupResetSynchronizer.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLAtomicAutomata_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_114.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_60.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/cc_banks_2.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AsyncResetSynchronizerShiftReg_w4_d3_i0.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_65.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLToAXI4.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/cc_banks_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_39.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/HellaPeekingArbiter.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_79.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLWidthWidget_8.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TileClockGater.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/UARTTx.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/DigitalTop.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_22.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_108.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLToAXI4_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_120.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/MulDiv.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_46.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/PeripheryBus.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AsyncResetRegVec_w1_i0.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/head_combMem_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ListBuffer.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/DivSqrtRecFN_small.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/RoundAnyRawFNToRecFN.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLAtomicAutomata.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/IntSyncAsyncCrossingSink_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLFIFOFixer_2.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Directory.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/DivSqrtRecFN_small_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/cc_dir.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_106.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/MulAddRecFNToRaw_postMul_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AsyncResetRegVec_w2_i0.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ClockGroupParameterModifier_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/data_arrays_0_0.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/RecFNToIN_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/PMPChecker_2.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLDebugModule.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/IntToFP.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLROM.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_55.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_14.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ClockGroupAggregator_6.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLFragmenter_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/MulAddRecFNPipe.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLXbar.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ClockSinkDomain_2.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/FixedClockBroadcast_3.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AXI4Buffer.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/CoherenceManagerWrapper.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_33.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLInterconnectCoupler_4.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/FrontBus.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AXI4UserYanker.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_115.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/CaptureChain.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/DivSqrtRecFNToRaw_small_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Repeater_3.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ClockGroupParameterModifier.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/CLINT.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_117.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_123.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/tag_array_0.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLInterconnectCoupler_14.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/regfile_combMem.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLDebugModuleInner.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLCacheCork.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/MSHR.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLInterconnectCoupler_9.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/PTW.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Repeater.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/cc_banks_3.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_sink_combMem.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ListBuffer_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLBuffer_12.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/SourceC.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_63.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/OptimizationBarrier.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Repeater_4.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLAsyncCrossingSink.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/MemoryBus.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_34.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/SystemBus.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLXbar_10.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/DCache.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/SourceA.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Repeater_8.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_5.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLFragmenter_6.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/IntXbar.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ShiftQueue.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AsyncQueue.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AXI4Fragmenter.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLFragmenter_5.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/head_combMem_0.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/MulAddRecFNToRaw_preMul.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLXbar_3.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_54.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/InclusiveCacheBankScheduler.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_43.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLBuffer_7.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/CaptureUpdateChain.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/RVCExpander.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLPLIC.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/RecFNToRecFN.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_0.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/tail_combMem.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLBusBypassBar.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/CompareRecFN.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/GenericSerializer.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/MulAddRecFNPipe_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/head_combMem.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_71.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLError_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/PMPChecker.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TilePRCIDomain.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_2.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_104.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/SynchronizerShiftReg_w8_d3.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/FPToInt.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_61.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AsyncQueueSource_4.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/BundleBridgeNexus_15.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ClockSinkDomain_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AsyncQueueSink_4.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/OptimizationBarrier_42.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLXbar_2.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLBuffer_9.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/FPUFMAPipe.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLXbar_5.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_59.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_4.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLFIFOFixer_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ICache.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLInterconnectCoupler_5.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_80.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AXI4IdIndexer.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/next_combMem.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLBuffer_16.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLInterconnectCoupler_11.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLXbar_8.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/CaptureUpdateChain_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLAsyncCrossingSource.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/MulAddRecFNToRaw_postMul.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLB_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_62.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/JtagStateMachine.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/InclusiveCache.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_27.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_26.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_125.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_28.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/IntSyncCrossingSource_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLError.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/FixedClockBroadcast_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/RoundAnyRawFNToRecFN_2.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AsyncResetSynchronizerShiftReg_w1_d3_i0.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/MulAddRecFNToRaw_preMul_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLDebugModuleInnerAsync.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLBuffer_4.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AsyncQueueSink_2.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_75.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLBuffer_6.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/SourceE.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AXI4IdIndexer_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Repeater_9.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AsyncQueueSource_2.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ResetCatchAndSync_d3.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_105.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Repeater_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_data_combMem.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Frontend.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AXI4IdIndexer_2.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/table_combMem.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ClockCrossingReg_w43.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ClockCrossingReg_w15.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ClockCrossingReg_w32.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/BTB.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/DCacheDataArray.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ClockGroupCombiner.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/RoundRawFNToRecFN.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_41.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AsyncQueueSource.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/SinkC.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/IntSyncCrossingSource_5.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/DivSqrtRecFNToRaw_small.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_10.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/DivSqrtRawFN_small.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLFIFOFixer_5.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/tail_combMem_0.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_30.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_126.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLFIFOFixer.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AsyncResetSynchronizerPrimitiveShiftReg_d3_i0.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_122.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/next_combMem_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/OptimizationBarrier_43.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Rocket.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ALU.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLSerdesser.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_112.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/next_combMem_0.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/RoundAnyRawFNToRecFN_3.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_31.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AsyncValidSync.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/SourceB.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/IntSyncSyncCrossingSink.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/data_arrays_0.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Arbiter.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/JtagBypassChain.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_64.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/DMIToTL.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_56.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_109.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/RoundAnyRawFNToRecFN_4.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/cc_banks_0.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/JtagTapController.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/FPU.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ClockCrossingReg_w55.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_17.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AsyncResetRegVec_w1_i1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLWidthWidget_4.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ProbePicker.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/MaxPeriodFibonacciLFSR.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_110.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_116.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/rf_combMem.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_83.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Repeater_7.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_74.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/IntSyncCrossingSource_4.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_23.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/FixedClockBroadcast.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ListBuffer_2.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_6.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLDebugModuleOuterAsync.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/data_combMem_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AMOALU.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_77.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLXbar_11.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/BankedStore.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_38.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/data_combMem.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_6.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_81.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/SinkD.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/INToRecFN_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AXI4UserYanker_2.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLInterconnectCoupler_12.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_69.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/SourceX.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLFragmenter_2.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/FPUDecoder.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/RecFNToIN.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/Queue_121.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLFragmenter_7.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/ram_combMem_24.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/AXI4Deinterleaver.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/tail_combMem_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/SinkX.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/IntSyncSyncCrossingSink_1.sv
lappend VERILOG_FILES $REPO_DIR/rocket/source/IP/$ROCKET_CONFIG/gen-collateral/TLXbar_4.sv

lappend VERILOG_FILES $REPO_DIR/rocket/source/rtl/verilog/mem_ext_big.v
lappend VERILOG_FILES $REPO_DIR/rocket/source/rtl/verilog/rocket_trace.v
lappend VERILOG_FILES $REPO_DIR/rocket/source/rtl/verilog/rocket_ctrl.v
lappend VERILOG_FILES $REPO_DIR/rocket/source/rtl/verilog/rocket_core.v
lappend VERILOG_FILES $REPO_DIR/rocket/source/rtl/verilog/rocket_regfile.v
lappend VERILOG_FILES $REPO_DIR/rocket/source/rtl/verilog/rocket_wrap.v
lappend VERILOG_FILES $REPO_DIR/rocket/source/rtl/verilog/pm_rocket.v

